import { createElement } from 'lwc';
import Roop02_wireAsFunction from 'c/roop02_wireAsFunction';

describe('c-roop02-wire-as-function', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-roop02-wire-as-function', {
            is: Roop02_wireAsFunction
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});